Running test on mutant:
============================= test session starts ==============================
platform linux -- Python 3.8.19, pytest-8.3.3, pluggy-1.5.0
rootdir: /mnt/temp/inspect_mutant
collected 1 item

../test.py F

=================================== FAILURES ===================================
_____________________________________ test _____________________________________

    def test():
        real_version_info = sys.version_info
        sys.version_info = MockVersionInfo()
        origin = _get_type_origin(MockType())
        sys.version_info = real_version_info
>       assert origin == "extra"
E       AssertionError: assert <test.MockType object at 0x7e40f871c820> == 'extra'

../test.py:17: AssertionError
=============================== warnings summary ===============================
../../../../home/marvin/workspace/guut-evaluation/emse_projects_data/venvs/dataclasses-json/lib/python3.8/site-packages/stringcase.py:247
  /home/marvin/workspace/guut-evaluation/emse_projects_data/venvs/dataclasses-json/lib/python3.8/site-packages/stringcase.py:247: DeprecationWarning: invalid escape sequence \W
    return re.sub("\W+", "", string)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
FAILED ../test.py::test - AssertionError: assert <test.MockType object at 0x7...
========================= 1 failed, 1 warning in 0.10s =========================
