Running test on mutant:
============================= test session starts ==============================
platform linux -- Python 3.8.19, pytest-8.3.3, pluggy-1.5.0
rootdir: /mnt/temp/inspect_mutant
collected 1 item

../../test.py F

=================================== FAILURES ===================================
_____________________________________ test _____________________________________

    def test():
        checker.Manager._job_count = lambda self: 1
        manager = checker.Manager(SimpleNamespace(options=SimpleNamespace(exclude=[], extend_exclude=[])), [], [])
        checker._try_initialize_processpool = lambda jobs: SimpleNamespace(imap_unordered=do_imap, terminate=do_terminate)
        try:
            manager.run_parallel()
        except Exception:
            pass
>       assert terminated
E       assert False

../../test.py:20: AssertionError
=========================== short test summary info ============================
FAILED ../../test.py::test - assert False
============================== 1 failed in 0.04s ===============================
