Running test on mutant:
============================= test session starts ==============================
platform linux -- Python 3.8.19, pytest-8.3.3, pluggy-1.5.0
rootdir: /mnt/temp/inspect_mutant
collected 1 item

../test.py F

=================================== FAILURES ===================================
_____________________________________ test _____________________________________

    def test():
        with patch("typing.overload", wraps=mock_overload):
            import flutes.multiproc
>       assert count == 22
E       assert 21 == 22

../test.py:13: AssertionError
=========================== short test summary info ============================
FAILED ../test.py::test - assert 21 == 22
============================== 1 failed in 0.08s ===============================
